# optimised docker-compose.yml
version: '3.8'

services:
  formygames:
    build:
      context: .
      args:
        PHP_VERSION: 8.2
        PHALCON_VERSION: 5.8.0
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ENVIRONMENT: ${ENVIRONMENT:-development}
    image: api.for-my.games:latest
    container_name: api.for-my.games
    ports:
      - "8909:8909"
    volumes:
      - .:/opt/formygames/src:z
      - composer-cache:/root/.composer/cache:z
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8909/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  composer-cache:
    driver: local

networks:
  default:
    driver: bridge